version: '3.8'

services:
  # MySQL Veritabanı
  db:
    image: mysql:8.0
    container_name: story-platform-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: story_platform
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: story_user
      MYSQL_PASSWORD: story_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - story_network
    command: --default-authentication-plugin=mysql_native_password

  # Redis Önbellek
  redis:
    image: redis:alpine
    container_name: story-platform-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - story_network

  # Backend API (Next.js)
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: story-platform-backend
    restart: unless-stopped
    depends_on:
      - db
      - redis
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://story_user:story_password@db:3306/story_platform
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=gizli_anahtar_buraya_yazilmali
      - CORS_ORIGIN=http://localhost:8080
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - story_network

  # Admin Panel (PHP Filament)
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: story-platform-admin
    restart: unless-stopped
    depends_on:
      - db
      - redis
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=story_platform
      - DB_USERNAME=story_user
      - DB_PASSWORD=story_password
      - REDIS_HOST=redis
      - API_URL=http://backend:3000/api
    ports:
      - "8000:80"
    volumes:
      - ./admin:/var/www/html
      - admin_storage:/var/www/html/storage
    networks:
      - story_network

  # Frontend (Vue.js)
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: story-platform-frontend
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:3000/api
      - VITE_WEBSOCKET_URL=ws://localhost:3000
    ports:
      - "8080:80"
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - story_network
    depends_on:
      - backend

networks:
  story_network:
    driver: bridge

volumes:
  db_data:
  redis_data:
  admin_storage: 